name: cinemana
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  dartz: ^0.10.1
  mockito: ^5.4.4
  dio: ^5.7.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  infinite_scroll_pagination: ^4.0.0
  cached_network_image: ^3.4.1
  bloc_concurrency: ^0.2.5
  # flutter_svg: ^2.0.10+1
  # material_floating_search_bar_2: ^0.5.0
  go_router: ^14.2.7
  flutter_toggle_tab: ^1.4.1
  # dio_cache_interceptor: ^3.5.0
  # video_player_media_kit: ^1.0.5
  # media_kit_libs_linux: ^1.1.3
  # video_player: ^2.9.1
  # media_kit_libs_android_video: ^1.3.6
  keep_screen_on: ^3.0.0
  easy_dynamic_theme: ^2.3.1
  # smooth_video_progress: ^0.0.4
  audio_video_progress_bar: ^2.0.3
  # media_kit: ^1.1.11
  media_kit:
    path: /home/hasan/Downloads/code/dart/flutter/media-kit/media_kit
  # media_kit_video: ^1.2.5
  media_kit_video:
    path: /home/hasan/Downloads/code/dart/flutter/media-kit/media_kit_video
  # media_kit_libs_video: ^1.0.5
  # media_kit_libs_video:
  #   path: /home/hasan/Downloads/code/dart/flutter/media_kit/media_kit_libs_video
  # media_kit_libs_android_video: ^1.3.6
  media_kit_libs_video: ^1.0.5
  sealed_languages: ^1.5.0
  file_picker: ^8.1.2
  go_provider: ^1.6.0
  readmore: ^3.0.0
  glass: ^2.0.0+1
  shared_preferences: ^2.3.2
  internet_connection_checker: ^1.0.0+1
  logging: ^1.2.0
  flutter_riverpod: ^2.5.1
  riverpod_infinite_scroll: ^1.0.11
  modal_bottom_sheet: ^3.0.0
  grouped_list: ^6.0.0
  sticky_grouped_list: ^3.1.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  bloc_test: ^9.1.7

flutter:
  uses-material-design: true

  fonts:
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf
        - asset: assets/fonts/Amiri-Italic.ttf
          style: italic
        - asset: assets/fonts/Amiri-Bold.ttf
          weight: 600
        - asset: assets/fonts/Amiri-BoldItalic.ttf
          style: italic
          weight: 600
    - family: Adobe Arabic
      fonts:
        - asset: assets/fonts/AdobeArabic-Regular.ttf
        - asset: assets/fonts/AdobeArabic-Bold.ttf
          weight: 800

  # assets:
  #   - assets/images/cinemana.png