name: cinemana
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  dartz: ^0.10.1
  mockito: ^5.4.4
  dio: ^5.7.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  infinite_scroll_pagination: ^4.0.0
  cached_network_image: ^3.4.1
  bloc_concurrency: ^0.2.5
  flutter_svg: ^2.0.10+1
  material_floating_search_bar_2: ^0.5.0
  go_router: ^14.2.7
  flutter_toggle_tab: ^1.4.1
  dio_cache_interceptor: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  bloc_test: ^9.1.7

flutter:
  uses-material-design: true

  assets:
    - assets/images/cinemana.png