name: cinemana
description: "A Flutter Client for Shabakaty Cinemana."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.7.0
  easy_dynamic_theme: ^2.3.1
  equatable: ^2.0.5
  file_picker: ^8.1.2
  flutter_riverpod: ^2.5.1
  get_it: ^7.7.0
  go_router: ^14.2.7
  infinite_scroll_pagination: ^4.0.0
  internet_connection_checker: ^1.0.0+1
  keep_screen_on: ^3.0.0
  logging: ^1.2.0
  media_kit:
    path: /home/hasan/Downloads/code/dart/flutter/media-kit/media_kit
  # media_kit: ^1.1.11
  media_kit_libs_video: ^1.0.5
  media_kit_video:
    path: /home/hasan/Downloads/code/dart/flutter/media-kit/media_kit_video
  # media_kit_video: ^1.2.5
  mockito: ^5.4.4
  permission_handler: ^11.3.1
  riverpod_infinite_scroll: ^1.0.11
  sealed_languages: ^1.5.0
  shared_preferences: ^2.3.2
  
dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.12
  flutter_launcher_icons: "^0.14.1"

  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf
        - asset: assets/fonts/Amiri-Italic.ttf
          style: italic
        - asset: assets/fonts/Amiri-Bold.ttf
          weight: 600
        - asset: assets/fonts/Amiri-BoldItalic.ttf
          style: italic
          weight: 600
    - family: Adobe Arabic
      fonts:
        - asset: assets/fonts/AdobeArabic-Regular.ttf
        - asset: assets/fonts/AdobeArabic-Bold.ttf
          weight: 800
  # assets:
  #   - assets/images/cinemana.png
